version: '3'
services:
  app:
    build: .
    container_name: application
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:15
    env_file: ./config/db.env
    container_name: database
    restart: always
    volumes:
      - ./test:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
