version: '3'
services:
  app:
    build: .
    container_name: application
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: database
    restart: always
    env_file: ./config/db.env
    ports:
      - 5432:5432
